spring:
  application:
    name: departement-ms
  profiles:
    active: dev
  datasource:
    url: 'jdbc:h2:mem:jcdb'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8087

logging:
  level:
    com.jc.departmentms: DEBUG
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG